name: flutter_portfolio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^3.0.1
  http: ^0.12.0
  share: ^0.6.5+4

  # For Firebase
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.1

  # For Auth
  email_validator: ^1.0.6
  flushbar: ^1.10.4
  tuple: ^1.0.3


  # For UI
  cupertino_icons: ^0.1.3

  # For DateTime
  intl: ^0.16.1
  flutter_local_notifications: ^4.0.1+2
  flutter_native_timezone: ^1.0.4

  # For Architecture
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  assets:
    - images/